name: CI test and publish Docker image

on: [push]

jobs:
  publish_dev:
    name: Publish dev branch to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: markxoe/cgm-remote-monitor-dev
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Clean git Checkout
        uses: actions/checkout@v2
      - name: Install Docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build, tag and push the dev Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 --no-cache=true -t ${{ env.DOCKER_IMAGE }}:dev_${{ github.sha }} .
          docker image push ${{ env.DOCKER_IMAGE }}:dev_${{ github.sha }}
          docker tag ${{ env.DOCKER_IMAGE }}:dev_${{ github.sha }} ${{ env.DOCKER_IMAGE }}:latest_dev
          docker image push ${{ env.DOCKER_IMAGE }}:latest_dev
